[workspace]

members = [
    # When adding a new crate which is published, you might need to:
    # 1. run `cargo changelog --write my_crate`
    # 2. Edit `my_crate/CHANGELOG.md` and change `## Unreleased` to `## 0.0.0 (2023-05-02)` (use
    # current date).
    # 3. Publish `my_crate` locally using `cargo publish -p my_crate`.
    # 4. Tag the commit with `my_crate-v0.0.0` and push the tag.
    # Then in the future you can just run the release workflow normally.
    "benches",
    "hydro_cli",
    "hydro_cli_examples",
    "hydroflow",
    "hydroflow_cli_integration",
    "hydroflow_datalog",
    "hydroflow_datalog_core",
    "hydroflow_internalmacro",
    "hydroflow_lang",
    "hydroflow_macro",
    "lattices",
    "multiplatform_test",
    "pusherator",
    "relalg",
    "variadics",
]



resolver = "2"

[patch.crates-io]
serde = { package = "serde", rev = "72fa9b09a78cb019dc918c3ce829cdfbc9cd96aa", git = "https://github.com/zzlk/serde.git", optional = true }
serde_derive = { package = "serde_derive", rev = "72fa9b09a78cb019dc918c3ce829cdfbc9cd96aa", git = "https://github.com/zzlk/serde.git", optional = true }


[profile.release]
strip = true      # Strip symbols from the binary
# Previously this was "z" to minimize docker binary size while sacrificing performance. But "z"
# doesn't make things that much smaller, `strip` is far more important for binary size. Use "3" for
# performance.
opt-level = 3
lto = "fat"

[profile.profile]
inherits = "release"
debug = 2
strip = "none"

[profile.profile.package."*"]
debug = 2
strip = "none"
